"""empty message

Revision ID: 6bfaa9c7ddf7
Revises: 
Create Date: 2026-01-14 11:45:41.104635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfaa9c7ddf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_ticket',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('price', sa.String(length=20), nullable=False),
                    sa.Column('activity_time', sa.String(
                        length=255), nullable=False),
                    sa.Column('activity_time_unit', sa.String(
                        length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ticket_request',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('category_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('client_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('client_phone', sa.String(
                        length=50), nullable=False),
                    sa.Column('sms_content', sa.Text(), nullable=True),
                    sa.Column('status', sa.Enum('PENDING', 'VALIDATED',
                                                'REFUSED', name='requeststatus'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('validated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['category_ticket.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ticket',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('access_key', sa.String(
                        length=255), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('category_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('expires_in', sa.DateTime(), nullable=False),
                    sa.Column('available', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('request_id', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['category_ticket.id'], ),
                    sa.ForeignKeyConstraint(
                        ['request_id'], ['ticket_request.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('ticket_request')
    op.drop_table('category_ticket')
    # ### end Alembic commands ###
