"""empty message

Revision ID: 919aae62e1a0
Revises: dfb472fec7f4
Create Date: 2026-01-02 01:39:18.880642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '919aae62e1a0'
down_revision: Union[str, Sequence[str], None] = 'dfb472fec7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_ticket', 'price',
                    existing_type=sa.FLOAT(),
                    type_=sqlmodel.sql.sqltypes.AutoString(length=20))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_ticket', 'price',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
                    type_=sa.FLOAT())
    # ### end Alembic commands ###
