"""empty message

Revision ID: 943b1e4f023f
Revises: ee9a50efe977
Create Date: 2026-01-02 00:43:44.211329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943b1e4f023f'
down_revision: Union[str, Sequence[str], None] = 'ee9a50efe977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_ticket', sa.Column(
        'price', sa.Float(), default=0.0, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_ticket', 'price')
    # ### end Alembic commands ###
