"""empty message

Revision ID: dfb472fec7f4
Revises: 943b1e4f023f
Create Date: 2026-01-02 01:25:27.364266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dfb472fec7f4'
down_revision: Union[str, Sequence[str], None] = '943b1e4f023f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_ticket', sa.Column('activity_time_unit',
                  sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_ticket', 'price',
                    existing_type=sa.FLOAT(),
                    nullable=True)
    op.drop_column('category_ticket', 'activity_time_unit')
    # ### end Alembic commands ###
