"""empty message

Revision ID: f4557cf0dc67
Revises: 
Create Date: 2026-01-05 22:37:16.124163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4557cf0dc67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_ticket',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('price', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=False),
                    sa.Column('activity_time', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('activity_time_unit', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ticket',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('expires_in', sa.DateTime(), nullable=False),
                    sa.Column('available', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['category_ticket.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('category_ticket')
    # ### end Alembic commands ###
